[Constants]
global $ups_ready = 0

[KeyEnableUpscale]
; Press after you are in-world to arm SBS packer
Key = NO_MODIFIERS VK_F8
type = cycle
$ups_ready = 0, 1

[Present]
if $ups_ready == 1
	run = CustomShaderUpscale
endif

[Resource3DVisionUpscaleBackupTexture]
[CustomShaderUpscale]
vs = upscale.hlsl
ps = upscale.hlsl
hs = null
ds = null
gs = null
blend = disable
cull = none
sampler = anisotropic_filter
topology = triangle_strip
o0 = set_viewport r_bb
Resource3DVisionUpscaleBackupTexture = reference ps-t101
ps-t101 = f_bb
draw = 4, 0
post ps-t101 = reference Resource3DVisionUpscaleBackupTexture
special = upscaling_switch_bb
